
build:
	./mvnw clean package

run:
	./mvnw spring-boot:run

db:
	open http://localhost:8080/h2-console/

catalogue:
	open https://eurodell.co.nz/wp-content/uploads/2021/01/EURODELL-Product-List-2021.pdf
